In [5]:
import numpy as np

# 创建 3x4 的二维数组，元素为 1 到 12 的整数
arr = np.arange(1, 13).reshape(3, 4)

print("原始数组:")
print(arr)

# 任务 1: 打印数组的形状、维度和数据类型
print("\n任务 1: 数组属性")
print("形状:", arr.shape)  # (3, 4)
print("维度:", arr.ndim)   # 2 (二维数组)
print("数据类型:", arr.dtype)  # int32 或 int64 (取决于系统)

# 任务 2: 将数组元素乘以 2，打印结果
arr_multiplied = arr * 2
print("\n任务 2: 乘以 2 后的数组")
print(arr_multiplied)

# 任务 3: 将数组重塑为 4x3 的形状，打印新数组
arr_reshaped = arr.reshape(4, 3)
print("\n任务 3: 重塑为 4x3 的数组")
print(arr_reshaped)

原始数组:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

任务 1: 数组属性
形状: (3, 4)
维度: 2
数据类型: int32

任务 2: 乘以 2 后的数组
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

任务 3: 重塑为 4x3 的数组
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
import numpy as np

# 创建 4x4 的二维数组
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

print("原始数组:")
print(array)

# 任务 1: 提取第 2 行所有元素（索引从0开始，第2行索引为1）
row_2 = array[1, :]
print("\n任务 1: 第 2 行所有元素")
print(row_2)

# 任务 2: 提取第 3 列所有元素（索引为2）
col_3 = array[:, 2]
print("\n任务 2: 第 3 列所有元素")
print(col_3)

# 任务 3: 提取子数组（包含第1、2行和第2、3列）
sub_array = array[0:2, 1:3]
print("\n任务 3: 子数组（第1-2行，第2-3列）")
print(sub_array)

# 任务 4: 将大于 10 的元素替换为 0
modified_array = array.copy()  # 创建副本以避免修改原始数组
modified_array[modified_array > 10] = 0
print("\n任务 4: 修改后的数组（大于10的元素替换为0）")
print(modified_array)

原始数组:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

任务 1: 第 2 行所有元素
[5 6 7 8]

任务 2: 第 3 列所有元素
[ 3  7 11 15]

任务 3: 子数组（第1-2行，第2-3列）
[[2 3]
 [6 7]]

任务 4: 修改后的数组（大于10的元素替换为0）
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  0  0]
 [ 0  0  0  0]]


In [9]:
import numpy as np

# 创建数组 A：3x2 的二维数组，元素为 1 到 6
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# 创建数组 B：一维数组 [10, 20]
B = np.array([10, 20])

print("数组 A:")
print(A)
print("\n数组 B:")
print(B)

# 任务 1: 计算 A 和 B 的逐元素相加（利用广播）
add_result = A + B
print("\n任务 1: A + B")
print(add_result)

# 任务 2: 计算 A 和 B 的逐元素相乘（利用广播）
multiply_result = A * B
print("\n任务 2: A * B")
print(multiply_result)

# 任务 3: 计算 A 的每一行与 B 的点积
dot_products = np.dot(A, B)
print("\n任务 3: A 的每一行与 B 的点积")
print(dot_products)

数组 A:
[[1 2]
 [3 4]
 [5 6]]

数组 B:
[10 20]

任务 1: A + B
[[11 22]
 [13 24]
 [15 26]]

任务 2: A * B
[[ 10  40]
 [ 30  80]
 [ 50 120]]

任务 3: A 的每一行与 B 的点积
[ 50 110 170]
